DROP TABLE IF EXISTS Accounts;
CREATE TABLE Accounts (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Bank VARCHAR(10) NOT NULL DEFAULT 'None',
    AccountNr VARCHAR(34) NOT NULL DEFAULT '00000',
    EntryDate DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Reference VARCHAR(4096) NOT NULL DEFAULT "FFDM default reference text",
    Amount FLOAT NOT NULL DEFAULT 0,
    Currency VARCHAR(4) NOT NULL DEFAULT 'EUR'
);

DROP TABLE IF EXISTS AssetReferences;
CREATE TABLE AssetReferences (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    AssetID VARCHAR(12) NOT NULL DEFAULT 'NO0000000000',
    AssetType VARCHAR(3) NOT NULL DEFAULT '',
    AssetName VARCHAR(254) NOT NULL DEFAULT 'FFDM default asset name',
    BankRef VARCHAR(254) DEFAULT NULL,
    NetRef1 VARCHAR(254) NOT NULL DEFAULT '',
    NetRef2 VARCHAR(254) NOT NULL DEFAULT ''
);

DROP TABLE IF EXISTS AssetPrices;
CREATE TABLE AssetPrices (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    AssetID VARCHAR(12) NOT NULL DEFAULT 'NO0000000000',
    PriceTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    AssetPrice FLOAT NOT NULL DEFAULT 0,
    Currency VARCHAR(4) NOT NULL DEFAULT 'EUR'
);

DROP TABLE IF EXISTS AssetTypes;
CREATE TABLE AssetTypes (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    AssetType VARCHAR(3) NOT NULL DEFAULT '',
    AssetTypeName VARCHAR(254) NOT NULL DEFAULT ''
);

DROP TABLE IF EXISTS TargetPrices;
CREATE TABLE TargetPrices (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    AssetID VARCHAR(12) NOT NULL DEFAULT 'NO0000000000',
    TargetPriceLow FLOAT NOT NULL DEFAULT 0,
    TargetPriceHigh FLOAT NOT NULL DEFAULT 0,
    Currency VARCHAR(4) NOT NULL DEFAULT 'EUR'
);

DROP TABLE IF EXISTS Depots;
CREATE TABLE Depots (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Bank VARCHAR(10) NOT NULL DEFAULT 'None',
    DepotNr VARCHAR(34) NOT NULL DEFAULT '00000',
    AssetID VARCHAR(12) NOT NULL DEFAULT 'NO0000000000',
    BankRef VARCHAR(254) NOT NULL DEFAULT '',
    AssetAmount FLOAT NOT NULL DEFAULT 0,
    AssetBuyPrice FLOAT NOT NULL DEFAULT 0,
    Currency VARCHAR(4) NOT NULL DEFAULT 'EUR'
);

DROP TABLE IF EXISTS VLplans;
CREATE TABLE VLplans (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PlanID INT(11) NOT NULL DEFAULT 'None',
    StartDate DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EndDate DATE DEFAULT NULL,
    AssetID VARCHAR(12) NOT NULL DEFAULT 'NO0000000000',
    Bank VARCHAR(10) NOT NULL DEFAULT "",
    AccountNr VARCHAR(34) NOT NULL DEFAULT "00000",
    Amount FLOAT NOT NULL DEFAULT 0,
    Pieces FLOAT NOT NULL DEFAULT 0,
    Currency VARCHAR(4) NOT NULL DEFAULT 'EUR'
);
